### ISSUE TITLE
Entered Text Does Not Display When Creating Wallet Password

### ISSUE THREAD

**Issue by Nathanael777** [owstack/ows-wallet#15]
When adding password protection to the wallet any entered text is not displayed in the box. The password is still entered and is still required to complete transactions.

This bug is recreatable across Android and iOS. 

Recreate:
1. Settings
2. Wallet
3. Request Spending Password (on)

![screenshot_2018-04-13-12-48-32](https://user-images.githubusercontent.com/38358766/38748001-b8325af4-3f1a-11e8-9ef2-dc2bd29f5bba.png)

**Comment by Indiglaze** [comment]
Same Issue on iOS.

![image uploaded from ios 10](https://user-images.githubusercontent.com/20173283/38748639-cc097204-3f1c-11e8-889e-345252ac1635.png)

**Comment by ajp8164** [comment]
Fixed
