### ISSUE TITLE
Fingerprint Protection Failure 

### ISSUE THREAD

**Issue by Indiglaze** [owstack/ows-wallet#16]
When adding fingerprint protection to a wallet it automatical turns off upon exiting. 

Recreate:
1. Go to settings and select a wallet 
2. Turn fingerprint on 
3. Exit to home 
4. Return to wallet settings 

![image uploaded from ios 7](https://user-images.githubusercontent.com/20173283/38748502-4c65bbf2-3f1c-11e8-9767-82d0a2f4b5ca.png)

![image uploaded from ios 9](https://user-images.githubusercontent.com/20173283/38748589-9c825956-3f1c-11e8-96ff-904848d1db52.png)

![image uploaded from ios 8](https://user-images.githubusercontent.com/20173283/38748512-51ba3862-3f1c-11e8-87de-288ac0cb46c0.png)

**Comment by ajp8164** [comment]
Fixed
