### ISSUE TITLE
Page Error

### ISSUE THREAD

**Issue by Indiglaze** [owstack/ows-wallet#18]
Black Screen when navigating home after opening the "Get Help"
Seems to Effect Scan/ Recieve/ Send at random intervals. 

Recreate:
1. Settings
2. Get Help
3. Click home

![img_0888](https://user-images.githubusercontent.com/20173283/40494893-f6d787cc-5f43-11e8-9f50-08e32b8db42c.PNG)

**Comment by ajp8164** [comment]
Fixed
