### ISSUE TITLE
Action Hang

### ISSUE THREAD

**Issue by Indiglaze** [owstack/ows-wallet#19]
If you navigate to help and then and of the bottom actions when you click on settings again they get stuck. 

Recreate
1. Go to Get Help
2. Choose Action 
3. Click on Settings again

![img_0889](https://user-images.githubusercontent.com/20173283/40495133-7ae872b0-5f44-11e8-822a-8f369e404fd4.PNG)
Notice Bottom right.

**Comment by ajp8164** [comment]
Same as issue #18 
Fixed in #18
